# Generated by Django 3.0.7 on 2020-09-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200908_0151'),
        ('authapp', '0005_auto_20200907_2109'),
    ]

    operations = [
    ]
