# Generated by Django 3.0.7 on 2020-09-16 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_merge_20200916_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 16, 27, 7, 499698, tzinfo=utc)),
        ),
    ]
